// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import fs from "fs";
import path from "path";
import { defineConfig } from "prisma/config";

// Manually parse .env to bypass dotenvx interception
(function loadEnv() {
  const envPath = path.join(__dirname, ".env");
  if (!fs.existsSync(envPath)) return;
  const lines = fs.readFileSync(envPath, "utf8").split("\n");
  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const idx = trimmed.indexOf("=");
    if (idx === -1) continue;
    const key = trimmed.substring(0, idx).trim();
    let val = trimmed.substring(idx + 1).trim();
    const commentIdx = val.indexOf(" #");
    if (commentIdx !== -1) val = val.substring(0, commentIdx).trim();
    if (!process.env[key]) process.env[key] = val;
  }
})();

console.log("=== prisma.config.ts loading ===");
console.log("DATABASE_URL:", process.env.DATABASE_URL);
console.log("=== prisma.config.ts done ===");

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "node prisma/seed.js",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
